#!/bin/sh
set -e

cargo build --release
perf stat -r3 --null target/release/core --max-heap-size=512M bench/binarytrees/binarytrees.core 21 2>&1 >/dev/null | grep "seconds time elapsed" | grep -Eo "[0-9]+[.,][0-9]+" | head -1

